function [forward_res] = DoForwardPass(net, tgtImg, unitedLayerInds, grads, params)
    disp('Forward Pass');

    res = [];
    forward_res = vl_simplenn(net,single(tgtImg),[],res,...
                          'accumulate', false, ...
                          'mode', 'test', ...
                          'conserveMemory', 0, ...
                          'backPropDepth', 43, ...
                          'sync', 0, ...
                          'cudnn', 0) ;

end